### ISSUE TITLE
Multi-gpu mode distributes by maxi-batch?

### ISSUE THREAD

**Issue by emjotde** [amunmt/amunmt#36]
Based on my observations it seems that a whole maxi-batch is being handled by one GPU. That seems suboptimal, I would rather distribute mini-batches. For instance if a document fits into 2 maxi-batches only two GPUs are used despite specifying 4 in the config.

**Comment by hieuhoang** [comment]
fair point.

**Comment by hieuhoang** [comment]
fair point. A risk it would make overall translation speed slower. Lemme think about it, not priority @ the mo

**Comment by emjotde** [comment]
No, why? It's not different from the previous handling of single sentences that were all dispatched to different GPUs. Now you just dispatch batches, should not really matter from which maxi-batch they come. A maxi-batch should only be an organization unit that lives on the CPU, why would that even affect translation speed?

**Comment by hieuhoang** [comment]
More threading issues, more locking, more organisation. I'm also wary 'cos it makes GPU-specific minibatch sizing more difficult, which I think will be an issue in the future

**Comment by emjotde** [comment]
One global maxi-batch, instead of having them per device. Have the threads fetch a batch from the maxi-batch as soon as it is done with the current one. If the maxi-batch is exhausted, take the next. Let's assume we are not going to do device specific batch-sizes.

**Comment by emjotde** [comment]
To summarize:

```
Until all sentences have been processed:
  Preload n sentences in maxi-batch
  Sort by length
  Create mini-batches, put mini-batches into buffer
  while buffer contains mini-batches:
     fetch top mini-batch
     create translation task for mini-batch
     enqueue task in thread pool (one thread per gpu device
```
Asynchronously threads are doing the following:
```
Translate batch
When done with batch:
  split batch into sentences
  for each sentence
    put into priority queue, sorted by sentence id
    while top id is next sentence
       pop sentence from queue and output
```

**Comment by hieuhoang** [comment]
ok. done
