### ISSUE TITLE
Orphaned Eclipse configuration

### ISSUE THREAD

**Issue by mkaeshammer** [amunmt/amunmt#38]
I created an Eclipse project using the "import existing project option". 
Project -> Properties -> C/C++ Build warns 
> Orphaned configuration. No base extension cfg exists for com.nvidia.cuda.ide.seven_five.configuration.debug.2085852150

Tool Settings is empty and I cannot edit anything in this tab. 

Should this be solved on your side or am I missing a plugin or something similar?

**Comment by hieuhoang** [comment]
1. it requires nsight, a specialist eclipse version from nvidia
2. It doesn't compile 'cos the code uses c++14. I'm using it as a glorified editor.
 If you're ok with that, then create the nsight workspace in the root amun directory and import that project
