### ISSUE TITLE
Feature Request: Rest API

### ISSUE THREAD

**Issue by mehmedes** [amunmt/amunmt#39]
Dear AmuNMT Team,

Would it be possible to create a Rest API so that translations could be queried like this:
```
http://localhost:8045/translate?q=hello+world
```
?

**Comment by emjotde** [comment]
Hi,
I believe we have something quite similar to that. 
@tomekd : Would be good to have a small wiki entry on how to use the API that's hidden somewhere in the python bindings.

**Comment by mehmedes** [comment]
Would it be possible to integrate pre- and postpocessing to that API/server.py so that a translation request initiates the following steps?

1. normalizing punctuation
2. tokenization
3. truecasing (or lowercasing)
4. preprocessing (e.g. applying BPE)
5. TRANSLATION
6. postprocessing (e.g. sed 's/\@\@ //g')
7. detruecasing
8. detokenization

**Comment by kpu** [comment]
I think it would be cleaner to let the user specify command lines for pre and post processing.

**Comment by emjotde** [comment]
BPEs are actually integrated in the command line version, not sure it works for the web interface. As for the rest, sorry, this is not something I would want to spend time on. You are however welcome to modify the python scripts yourself and contribute.

**Comment by tomekd** [comment]
BPE works with Python bindings as well as with normal amun application.

**Comment by mehmedes** [comment]
Ok. Thanks!
