### ISSUE TITLE
amunmt_server issue: RuntimeError: /src/common/god.cpp:267: ret.threadInd >= gpuThreads

### ISSUE THREAD

**Issue by smatthay** [amunmt/amunmt#40]
Hi there!

We are experiencing an issue with running the AmuNMT server on one GPU and sending a file for translation to it line by line. To reproduce this issue, please perform the following steps:

1. Start Ubuntu VM with 1 GPU (Nvidia K80)

2. Create a config.yml similar to the following:

relative-paths: no

beam-size: 12
devices: [0]
normalize: yes
threads-per-device: 1
threads: 1
gpu-threads: 1
cpu-threads: 0

scorers:
  F0:
    path: <path_to_your_model>
    type: Nematus

weights:
  F0: 1.0

source-vocab: <path_to_your_json_file>
target-vocab: <path_to_your_json_file>

3. Translate a file using the config.yml and see it work:

./build/bin/amun -c config.yml < testfile.en

4. Start a AmuNMT server from the same config:

python scripts/amunmt_server.py -c config.yml -p 8080

5. Server is waiting for input:

[Fri Feb 17 12:32:51 2017] (I) Options:
allow-unk: false
beam-size: 12
cpu-threads: 0
devices: [0]
gpu-threads: 1
max-length: 500
maxi-batch: 1
mini-batch: 1
n-best: false
no-debpe: false
normalize: yes
relative-paths: no
return-alignment: false
scorers:
  F0:
    path: <path_to_your_model>
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab: <path_to_your_json_file>
target-vocab: <path_to_your_json_file>
threads: 1
threads-per-device: 1
weights:
  F0: 1.0
wipo: false
[Fri Feb 17 12:32:52 2017] (I) Loading scorers...
[Fri Feb 17 12:32:52 2017] (I) Loading model <path_to_your_model> onto gpu0
[Fri Feb 17 12:32:56 2017] (I) Reading from stdin

6. Call the server from a python script:

from websocket import create_connection
import time

with open("testfile.en") as f:
_for line in f:
__ ws = create_connection("ws://localhost:8080/translate")
__ ws.send(line)
__ result=ws.recv()
__ print(result)
__ ws.close()
__ time.sleep(5)

7. See the server output:

[Fri Feb 17 12:35:52 2017] (I) Setting CPU thread count to 0
[Fri Feb 17 12:35:52 2017] (I) Setting GPU thread count to 1
[Fri Feb 17 12:35:52 2017] (I) Total number of threads: 1
Batch 0.0: Search took 0.071s
Best translation: ...
Batch 0.0: Search took 0.016s
Best translation: ...
[Fri Feb 17 12:35:57 2017] (I) Setting CPU thread count to 0
[Fri Feb 17 12:35:57 2017] (I) Setting GPU thread count to 1
[Fri Feb 17 12:35:57 2017] (I) Total number of threads: 1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "scripts/amunmt_server.py", line 27, in handle_websocket
    trans = nmt.translate(message.split('\n'))
RuntimeError: /data/amunmt/src/common/god.cpp:267 in amunmt::DeviceInfo amunmt::God::GetNextDevice() const threw amunmt::util::Exception because `ret.threadInd >= gpuThreads'.
Too many GPU threads

**Comment by hieuhoang** [comment]
oops apologies. Hadn't looked at the python bindings for a while and they became outdated with some recent changes.

I've just pushed a fix to the dev branch
   https://github.com/amunmt/amunmt/commit/01a18b74adf6fd840b8fa075cbd9c7b4e63bdd56

**Comment by smatthay** [comment]
Thanks a lot, @hieuhoang, for your rapid fix! Works now.
