### ISSUE TITLE
translation of second line/list item unnecessary?

### ISSUE THREAD

**Issue by smatthay** [amunmt/amunmt#42]
Hi there!

When I translate one string, amunmt always translates two strings/lines in a list - even when I "line.rstrip()" my input string. Therefore, the overall search takes twice the time.

As a test hack (not the actual fix), I have changed this line:

https://github.com/amunmt/amunmt/blob/bcfe2f384f60f8e40a0fb7cba9833ec5fc0a7d2a/src/python/amunmt.cpp#L51

from 

`for(int i = 0; i < boost::python::len(in); ++i) {`

to 

`for(int i = 0; i < (boost::python::len(in) - 1); ++i) {`

Now the translation is much faster and I don't have that second unnecessary translation which returns some kind of useless token, only, anyway.

Maybe at some point, the string is not correctly converted to a list of strings with length = 1 in case there is only one line to be translated?

Best wishes,
Simon

**Comment by tomekd** [comment]
Hi Simon,

how do you process data? Are you sure that the list you pass to amunmt has exactly one element and doesn't contain an empty string as the second one? If you split string with split('\n'), Python puts an empty string if the input string ends with '\n'.

I check test for python binding and it is passing for me:
https://github.com/amunmt/amunmt-regression-tests/blob/master/tests/test_python_bindigs/test.py

Best,
Tomasz

**Comment by smatthay** [comment]
Hi Tomasz!

I am sending the strings to the amunmt_server:
https://github.com/amunmt/amunmt/blob/master/scripts/amunmt_server.py

Maybe the unnecessary second line gets added here (message.split('\n'))?
https://github.com/amunmt/amunmt/blob/master/scripts/amunmt_server.py#L26

Best wishes,
Simon

**Comment by tomekd** [comment]
Hi Simon,

That's right.
The solution is simple: just strip the '\n' symbol from the end of your string you send to the server. 
Later, I will add support for that situation.

Best,
Tomasz

**Comment by hieuhoang** [comment]
let me deal with this. It's affecting the batching as well

**Comment by hieuhoang** [comment]
I've made some changes to deal with
   1. the annoying newline char. The server will now accept data that ends with a new line
   2. Faster decoding with batching
You should use the client program at
   https://github.com/amunmt/amunmt/blob/dev/scripts/client.py
to take advantage of batching. Make the batch size the same as maxi-batch for fastest results. @smatthay I've used your test code to create this client code. Hope that's ok

**Comment by tomekd** [comment]
Ad. 1
Isn't better just to check if the last sentence after splitting is empty or not?

**Comment by hieuhoang** [comment]
change it to however u want

**Comment by emjotde** [comment]
What's the status of this?

**Comment by hieuhoang** [comment]
looks fixed to me
