### ISSUE TITLE
merging branches

### ISSUE THREAD

**Issue by hieuhoang** [amunmt/amunmt#48]
we should do this soon, it's been over 2 weeks since some of them have merged with master, conflicts will start to grow

**Comment by tomekd** [comment]
@hieuhoang : I thought it;s already done. To close?

**Comment by hieuhoang** [comment]
i've done the dev branch. Haven't done the test branches

**Comment by tomekd** [comment]
I've done the testing branch. There was only layer normalization implementation. Closing.
