### ISSUE TITLE
Adding tie_embeddings support

### ISSUE THREAD

**Issue by tomekd** [amunmt/amunmt#51]
A lot of people use ``tie_embeddings``, which looks helping in some cases. 

The model with tie_embeddings doesn't contain (at least) ``ff_logit_W``, which should be pointing to ``Wemb_dec`` (probably -- it has to confirm by looking into nematus code).

**Comment by emjotde** [comment]
Can we put this off for some time? I do not want to add new features, before we coordinate amunmt and marian.

**Comment by emjotde** [comment]
Closing this for the moment, we can re-open this later.
