### ISSUE TITLE
Add layer-normalization to master

### ISSUE THREAD

**Issue by emjotde** [amunmt/amunmt#52]
Add layer-normalization to master, we have it in a branch already. Should recognize automatically if layer-normalization was used (based on presence of certain parameters). Should retain compatibility with Marian, currently not required to maintain compatibility with Nematus.

**Comment by tomekd** [comment]
Mostly done.
The GPU version is compatible with model produced by marian (DL4MT).

There is still lack of cpu verison. I've already implemented simple version of layer normalization functions, but I have to add the norm layer in correct places in encoder/decoder.

**Comment by emjotde** [comment]
Maybe throw an exception in the CPU version for now if someone tries to use it with layer-normalization?

**Comment by emjotde** [comment]
GPU versions work for both types of models.

**Comment by tomekd** [comment]
To close or waiting for CPU?

**Comment by emjotde** [comment]
Do the CPU version, too.

**Comment by tomekd** [comment]
CPU support added.
