### ISSUE TITLE
Compile Error in all branches 

### ISSUE THREAD

**Issue by kadir-gunel** [amunmt/amunmt#58]
Hello, 

I have installed CMake 3.5.1, GCC/G++ 5.4, Boost 1.61, CUDA 8.0 under Ubuntu 16.04. And what ever I do, changing the branches and rebuild them, I cannot build the tool. In fact, the most interesting was the broken build after 100%, under branch 3a548b3 . 

The error log can be found at : https://drive.google.com/file/d/0B0eolFp3-Ym5NFlhYWJTTGtiS0E/view 

Could you please help? 

B.R.

**Comment by emjotde** [comment]
Hi again, thank you for re-opening the issue. 

Based on the error log I would insist this is a boost issue with zlib and not directly connected to AmuNMT. 

Most likely you built your custom boost installation withouth having zlib dev headers installed. I thing you would need to make sure that you have zlib installed, rebuild boost and then try again. The only errors in the error log are complaints from boost that it cannot find symbols from zlib. Boost should do that by itself.

**Comment by kadir-gunel** [comment]
Thank you for the great tool!

Before I was getting those errors I have already installed zlib. But you are right, I installed it after I build the boost. Now, I am building boost 1.63 with zlib installed. 
Do you think I should stick with boost 1.61? I saw one thread, probably yours, saying that boost 1.63 solved the issue. Thus, I wanted to give a shot.

**Comment by tomekd** [comment]
I'm using boost 1.63 (Arch Linux) on my desktop and there is no problem with amun.

**Comment by kadir-gunel** [comment]
I am trying to build the stable branch. Now, I am getting again an error after 98% of comilation. I again share the cmake output and the error log : 
https://drive.google.com/file/d/0B0eolFp3-Ym5SHFXZmN4WFZMZHc/view?usp=sharing
https://drive.google.com/file/d/0B0eolFp3-Ym5Wi0yMkpJdmxNX3c/view?usp=sharing

**Comment by emjotde** [comment]
This is the error I was getting with Boost 1.61. Your cmake output says it is still using this version.

**Comment by kadir-gunel** [comment]
Well, that is so strange! I removed all files related with boost 1.61 . 
How did you solve it ?

**Comment by tomekd** [comment]
Maybe CMake cached boost paths. Try to  'hard' clean up build directory (``rm -fr build; mkdir build; cd build``)

**Comment by kadir-gunel** [comment]
1. 'hard' clean up solution does not work. 
2. I noticed that after building boost there were no sys-links under /usr/local/lib/libboost and also under 
no folder named boost /usr/local/include/ 
3. I again changed the version to 61, now I have sys-links but no boost folder under /usr/local/include.

**Comment by emjotde** [comment]
is there a reason you not using the system-wide boost 1.58 which comes with ubuntu 16.04?

**Comment by kadir-gunel** [comment]
Actually, I had 1.58 but this repo suggested to use 1.61.

**Comment by emjotde** [comment]
Oh indeed. Now I am wondering why actually. Anyway, boost 1.58 is perfectly fine and we should maybe change the recommendation as this is a packaged boost and a lot easer to install. 

One of the newer boost versions has a bug, not sure which one right now. I am using 1.63 without problems, but mostly because I just happened to update from a really old version. So maybe the safest way would be to get rid of all custom boosts and go back to the boost version of the distribution.

**Comment by kadir-gunel** [comment]
D'oh!  :smile:  
I installed it. 
Sorry, for the trouble. But I think you should definitely change it; since using apt-get is the easiest way to install libboost under ubuntu 16.04
Closing the issue.

**Comment by emjotde** [comment]
Great. I will change it in a minute.

**Comment by mehmedes** [comment]
@kadir-gunel Did boost 1.58 really work with you? 
The installation worked without errors using 1.58, but wen actually trying to train or translate I ended up with ´´´core dumped´´´.
I had to update cmake and upgrade to boost 1.63!

**Comment by emjotde** [comment]
I have no problems with any of those two versions. If I'm not wrong 1.61 is buggy. If you have problems due to boost it is more likely that your boost installations got mixed up with older versions.

**Comment by kadir-gunel** [comment]
@mehmedes First, I tried with boost 1.61 then with 1.63 and both were troublesome; no sys-links etc. 
What is your ubuntu version? I am using 16.04 and installed liboost via terminal without headache. And it works like a charm.

**Comment by kadir-gunel** [comment]
@mehmedes By the way, "core dump" issue might be caused by data paths in your model file.

**Comment by mehmedes** [comment]
I'm using 16.04. I don't know, 1.58 didn't work with me. With 1.63, everything's fine. I'll revert back to 1.58 and have another try.
