### ISSUE TITLE
DLMT, GNMT, MULTI_GNMT and their antonyms

### ISSUE THREAD

**Issue by kadir-gunel** [amunmt/amunmt#59]
Hello, 
I was wondering what are their "opened" names ? There was no explanation in the documentation.

B.R.

**Comment by emjotde** [comment]
Hi, 
these are already a bit outdated. With the next update those will be renamed, new names in parentheses:
 * dl4mt (= amun): This signifies a model that is compatible with the original dl4mt model by Cho&Firat, also the same model that is available in basic Nematus. Works with the `amun` translation tool, but does not allow for extra features like multi-layer etc. The `amun` translator has been handwritten and optmized and adding features like multi-layer support is difficult. 
 * gnmt (= s2s): The old name came from the google architecture, but it is not that faithful a reimplementation. This is a more general model, that can be more or less easily extended, for instance it has multi-layer support. In the feature it will be possible to define model architectures with a text file. These require the new `s2s_translator` binary (not yet in the `amunmt` repo, available in https://github.com/amunmt/marian). The translator is slower than `amun`, but uses the same architecture as the training tool. In theory definining a new model for training automatically means it can be used for translation with `s2s_translator`.
 * multi_gnmt (= multi_s2s): the same as above, but can have more than two input sentences at the same time. Also to be used with the `s2s_translator`.

This stuff is sort of purposefully not documented yet, as I have to make this a bit more userfriendly. Working on it.

**Comment by kadir-gunel** [comment]
Thank you for information.
