### ISSUE TITLE
determine the number of units in a layer for a model?

### ISSUE THREAD

**Issue by kadir-gunel** [amunmt/amunmt#60]
I was reading the documentation and couldn't find the parameter for determining the number of cells/units in a layer in a config file? 

B.R.

**Comment by tomekd** [comment]
You don't have to set it up. It's taken from a model.

**Comment by emjotde** [comment]
For training a model, use 

--dim-rnn N
--dim-emb M

This is the numer of units in all RNN layers (encoder and decoder) and the embedding size (again encoder and decoder). In the future I plan to make this more configurable.

**Comment by kadir-gunel** [comment]
Thank you.
