### ISSUE TITLE
Validation-script : m : stalled n times 

### ISSUE THREAD

**Issue by kadir-gunel** [amunmt/amunmt#62]
I am checking train.log file and I see that in some places there are entries like :  
  validation-script : 0  : stalled 6 times
and in some places : 
  validation-script: 7.72 : new best 

For the latter case, it is quite obvious. But I did not understand the meaning of  stalled 6 time. 
Could someone please explain ?

B.R.

**Comment by emjotde** [comment]
That's a counter, if the score does not improve it "stalls" as in "stops making progress". You can use that together with --early-stopping if you want your training process to terminate after it has stalled a number of times.

BTW, the six 0s at the beginning are expected?

**Comment by kadir-gunel** [comment]
Thank you.
