### ISSUE TITLE
The config file "mtsrc-pe.ensemble.ape.tuned.yml"

### ISSUE THREAD

**Issue by yiming-Tan** [amunmt/amunmt#66]
Hello, for the configuration file "mtsrc-pe.ensemble.ape.tuned.yml", what command should I use to translate .src files and .mt files?

**Comment by emjotde** [comment]
Hi,
make sure you are using commit revision 3833669 and then do

```
paste test.mt test.src | ./path/to/amun -c mtsrc-pe.ensemble.ape.tuned.yml
```
It assumes that the input goes to standard input, <tab>-separated, first field is *.mt second field is *.src . 

Thanks for asking, I should put that on the description site.

**Comment by yiming-Tan** [comment]
Thank you !
