### ISSUE TITLE
Force Amun to use cpu

### ISSUE THREAD

**Issue by choltz95** [amunmt/amunmt#72]
Hi, 

For some reason training a translation model with marius does fine, but I am having issues with amun translation & cuda driver compatibility. Is there a way I can do translations using only the cpu?

**Comment by emjotde** [comment]
Assuming you managed to compile amun, it should be enough to set `--cpu-threads 8 --gpu-threads 0`. But it seems you have other problems? Maybe we can help with those?

**Comment by choltz95** [comment]
Thanks. I must have missed --gpu-threads in the documentation. Unfortunately, I don't have privileges over my system, so I can't mess around with the cuda drivers myself. This approach will be fine. 

Thanks again for your help.
